# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://github.com/marketplace/actions/vitest-coverage-report

name: Node.js Test Coverage Report

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        branch:
          - ${{ github.head_ref }}
          - "main"
    permissions:
      # Required to checkout the code
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: "Install Deps"
        run: npm ci
      - name: "Build"
        run: npm run build
      - name: "Run Tests & Coverage"
        run: npm run test
      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: success() || failure() # run whether steps succeed or not
        with:
          result-type: lines
          gist-token: ${{ secrets.GIST_SECRET }} # if you want to upload badge to gist
          gist-url: https://gist.github.com/gokulk16/eaf6c29242b70728224cc81c3f9ba750
          upload-badge: true
          badge-text: "coverage"
          badge-path: "badge-${{ github.event.repository.name }}-${{ matrix.branch }}.svg"
      - name: "Upload Coverage"
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.branch }}
          path: coverage

  report-coverage:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      # To comment in pull request
      pull-requests: write
    steps:
      - name: "Download Coverage Artifacts"
        uses: actions/download-artifact@v4
        with:
          name: coverage-${{ github.head_ref }}
          path: coverage
      - uses: actions/download-artifact@v4
        with:
          name: coverage-main
          path: coverage-main
      - name: "Vitest Coverage Differences from main"
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-compare-path: coverage-main/coverage-summary.json
